import type { Metadata } from "next";
import { Righteous, Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import { AppNavbar } from "./components/navbar";

const righteous = Righteous({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-righteous",
});

const montserrat_Alternates = Montserrat_Alternates({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-montserrat_Alternates",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${righteous.variable} ${montserrat_Alternates.variable}`}
      >
        <AppNavbar />
        {children}
      </body>
    </html>
  );
}
